######################################################################
# Automatically generated by qmake (3.0) Thu Jan 23 15:49:52 2014
######################################################################

TEMPLATE = app
TARGET = cube
CONFIG += debug
INCLUDEPATH += .
LIBS += -lSDL2 -lglut -lGLU -lGL
OBJECTS_DIR = obj

SOURCES += src/main.cpp \
    src/scene.cpp

HEADERS += \
    src/scene.h
